---

- name: Deploy, Modify, Validate L2LS Data Center(s)
  hosts: eos
  gather_facts: no
 
  tasks:

    - name: Set Hostname and System Settings (DNS, NTP, STP Mode, etc.)
      import_role:
        name: common
      tags: sysdefaults

    - name: Gather EOS Facts
      eos_facts:
      tags: facts

    - name: Configure Infrastructure Interfaces (Leaf/Spine Interconnects)
      import_role:
        name: infra_ints
      tags: infra_ints

    - name: Create VLANs in each Data Center
      import_role:
        name: vlans
      tags: vlans

- name: Configure MLAG (Non-MLAG Devices Skipped)
  hosts: mlag
  gather_facts: no
  
  tasks: 
    - name: Configure MLAG
      import_role:
        name: mlag
      tags: mlag
